# SmartMall API 测试框架 - GitHub Actions CI/CD
# 自动运行API测试并生成Allure报告

name: SmartMall API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests faker flask
        
    - name: Start Mock Server and Run Tests
      run: |
        # 启动Mock服务器
        cd mock_server
        python app.py &
        SERVER_PID=$!
        
        # 等待服务器启动
        echo "Waiting for Mock server to start..."
        sleep 10
        
        # 检查服务器是否运行
        if curl -f http://127.0.0.1:8080/health; then
          echo "Mock server is running successfully"
          
          # 运行测试
          cd ..
          python -m pytest -v --tb=short
          TEST_EXIT_CODE=$?
          
          # 停止服务器
          kill $SERVER_PID
          
          # 返回测试结果
          exit $TEST_EXIT_CODE
        else
          echo "Mock server failed to start"
          kill $SERVER_PID
          exit 1
        fi
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          allure-results/
          reports/
