# SmartMall API 测试框架 - GitHub Actions CI/CD
# 自动运行API测试并生成Allure报告

name: SmartMall API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests faker flask
        
    - name: Test Mock Server Startup
      run: |
        cd mock_server
        python -c "from app import app; print('Mock server imports successfully')"
        echo "Mock server code is valid"
        
    - name: Start Mock Server
      run: |
        cd mock_server
        nohup python app.py > server.log 2>&1 &
        echo $! > server.pid
        
    - name: Wait for server
      run: |
        echo "Waiting for Mock server to start..."
        for i in {1..30}; do
          if curl -f http://127.0.0.1:8080/health > /dev/null 2>&1; then
            echo "Mock server is running successfully"
            break
          fi
          echo "Attempt $i: Server not ready yet..."
          sleep 2
        done
        
    - name: Run tests
      run: |
        python -m pytest -v --tb=short
        
    - name: Stop server
      if: always()
      run: |
        if [ -f mock_server/server.pid ]; then
          kill $(cat mock_server/server.pid) || true
          rm mock_server/server.pid
        fi
        
    - name: Upload server logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: server-logs
        path: mock_server/server.log
