# SmartMall API 测试框架 - GitHub Actions CI/CD
# 自动运行API测试并生成Allure报告

name: SmartMall API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest allure-pytest requests faker flask
        
    - name: Start Mock Server
      run: |
        cd mock_server
        python app.py &
        sleep 5
        echo "Mock server started"
        
    - name: Wait for server to be ready
      run: |
        timeout 30 bash -c 'until curl -f http://127.0.0.1:8080/health; do sleep 1; done'
        echo "Mock server is ready"
        
    - name: Run tests with Allure reporting
      run: |
        python -m pytest --alluredir=allure-results --tb=short -v
        
    - name: Generate Allure Report
      if: always()
      run: |
        # 这里可以添加Allure报告生成，如果需要的话
        echo "Tests completed - check allure-results directory"
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/
